
services:
  fastapi-app:
    build: ./fastApi
    ports:
      - "${APP_PORT}:5000"
    volumes:
      - ./fastApi/app:/app
    depends_on:
      - minio
    networks:
      - pipeline-net
    env_file:
      - .env

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
     MINIO_ENDPOINT: ${MINIO_ENDPOINT}
     MINIO_ROOT_USER: ${MINIO_ROOT_USER}
     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
     MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    env_file:
      - .env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - pipeline-net
    
networks:
  pipeline-net:
    driver: bridge

volumes:
  minio_data:

