
services:
  fastapi-app:
    build: ./fastApi
    ports:
      - "${FASTAPI_APP_PORT}:${FASTAPI_APP_PORT}"
    volumes:
      - ./fastApi/app:/app
    depends_on:
      - minio
      - spark-master
    networks:
      - pipeline-net
    env_file:
      - .env

  minio:
    image: minio/minio
    ports:
      - "${MINIO_APP_PORT}:${MINIO_APP_PORT}"
      - "${MINIO_CONSOL_PORT}:${MINIO_CONSOL_PORT}"
    env_file:
      - .env
    command: server /data --console-address ":${MINIO_CONSOL_PORT}"
    volumes:
      - minio_data:/data
    networks:
      - pipeline-net
  
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=${SPARK_MASTER_MODE}
    env_file:
      - .env
    ports:
      - "${SPARK_MASTER_WEB_PORT}:${SPARK_MASTER_WEB_PORT}" # Spark Master Web UI
      - "${SPARK_MASTER_RPC_PORT}:${SPARK_MASTER_RPC_PORT}" # Spark Master RPC Port
    networks:
      - pipeline-net

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=${SPARK_WORKER_MODE}
    env_file:
      - .env
    depends_on:
      - spark-master
    networks:
      - pipeline-net
    
networks:
  pipeline-net:
    driver: bridge

volumes:
  minio_data:

